# Generated by Django 5.0.7 on 2024-08-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
