# Generated by Django 5.0.7 on 2024-07-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_booking_alter_categories_name_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
