# Generated by Django 5.0.7 on 2024-08-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
