# Generated by Django 5.0.7 on 2024-08-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_alter_doctorappointment_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorappointment",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
    ]
