# Generated by Django 5.0.7 on 2024-08-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_doctorappointment_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorappointment",
            name="role",
        ),
    ]
