# Generated by Django 5.0.7 on 2024-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_alter_doctorappointment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
