# Generated by Django 5.0.7 on 2024-08-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_appointment_doctor_appointment_nurse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="nurse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nurse_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
