# Generated by Django 5.0.7 on 2024-08-11 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_appointment_doctor_alter_appointment_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
